# Generated by Django 5.0.5 on 2024-05-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='covers/Annotation_2022-08-10_011419.png', upload_to='covers/'),
        ),
    ]
