# Generated by Django 4.2.13 on 2024-05-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_informationcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationcart',
            name='number_account_cart',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='informationcart',
            name='number_cart',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='informationcart',
            name='number_shabaa_cart',
            field=models.CharField(max_length=50),
        ),
    ]
