# Generated by Django 4.2.13 on 2024-05-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_alter_informationcart_number_account_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationcart',
            name='cvv2',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
