# Generated by Django 4.2.13 on 2024-05-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoproject', '0003_rename_todoitem_todoitems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitems',
            old_name='items',
            new_name='title_item',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='items',
        ),
        migrations.AddField(
            model_name='todoitems',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoproject.todolist'),
            preserve_default=False,
        ),
    ]
