# Generated by Django 4.2.13 on 2024-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoproject', '0006_alter_todolist_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='completed',
            field=models.CharField(choices=[('Finished', 'Finished'), ('Imcompleted', 'Imcompleted')], default='Imcompleted', max_length=20),
        ),
    ]
