# Generated by Django 4.2.13 on 2024-05-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoproject', '0008_remove_todoitems_title_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='title',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
