# Generated by Django 4.2.13 on 2024-05-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoproject', '0009_todoitems_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
    ]
