# Generated by Django 4.2.13 on 2024-05-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_code',
            new_name='ticket_id',
        ),
    ]
