# Generated by Django 4.2.13 on 2024-05-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_answeradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='choice_user_neccesiry',
            field=models.CharField(choices=[('low', 'ضروریت کم'), ('medium', 'ضروریت متوسط'), ('high', 'ضروریت زیاد')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
