# Generated by Django 4.2.13 on 2024-05-13 07:21

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_ticket_choice_user_neccesiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='choice_user_neccesiry',
            field=models.CharField(choices=[(1, 'ضروریت کم'), (2, 'ضروریت متوسط'), (3, 'ضروریت زیاد')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=ticket.models.generic_unique_code, max_length=10, unique=True),
        ),
    ]
