# Generated by Django 4.2.13 on 2024-05-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_ticket_choice_user_neccesiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='choice_user_neccesiry',
            field=models.CharField(choices=[(1, 'فوری'), (2, 'غیر فوری')], default=1, max_length=9),
        ),
    ]
