# Generated by Django 4.2.13 on 2024-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_choice_user_neccesiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='choice_user_neccesiry',
            field=models.CharField(choices=[('فوری', 1), ('غیرضروری', 2)], default=2, max_length=20),
        ),
    ]
