# Generated by Django 4.2.13 on 2024-05-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_choice_user_neccesiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeradmin',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_resolved_admin', to='ticket.ticket'),
        ),
    ]
