# Generated by Django 4.2.13 on 2024-05-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_remove_answeradmin_ticket_ticket_answer_admin_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='answer_admin_ticket',
        ),
    ]
