# Generated by Django 4.2.13 on 2024-05-15 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_remove_ticket_answer_admin_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer_admin_ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_admin_tickets', to='ticket.answeradmin'),
            preserve_default=False,
        ),
    ]
