# Generated by Django 4.2.13 on 2024-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_remove_ticket_answer_admin_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeradmin',
            old_name='answer_admin_ticket',
            new_name='ticket',
        ),
    ]
