# Generated by Django 4.2.13 on 2024-05-15 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_rename_answer_admin_ticket_answeradmin_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answeradmin',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_admin_tickets', to='ticket.ticket'),
        ),
    ]
